/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai4;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VanTT
 */
public class FrProduct extends javax.swing.JFrame {

    ArrayList<Book> listBook = new ArrayList<>();
    /**
     * Creates new form FrProduct
     */
    public FrProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPublisher = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfISBN = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAuthor = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btRead = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBooks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Add New Book");

        jLabel2.setText("ISBN:");

        jLabel3.setText("Book's name:");

        jLabel4.setText("Author:");

        cbPublisher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FPoly", "Kim Dong", "Thanh Nien" }));

        jLabel5.setText("Publisher:");

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRead.setText("Read");
        btRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReadActionPerformed(evt);
            }
        });

        tbBooks.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Book's Name", "Author", "Publisher"
            }
        ));
        jScrollPane1.setViewportView(tbBooks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btRead))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbPublisher, javax.swing.GroupLayout.Alignment.LEADING, 0, 222, Short.MAX_VALUE)
                                        .addComponent(tfAuthor)
                                        .addComponent(tfName)
                                        .addComponent(tfISBN))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            // TODO add your handling code here:
            String ISBN = tfISBN.getText();
            String bookName = tfName.getText();
            String author = tfAuthor.getText();
            String publisher = (String) cbPublisher.getSelectedItem();

            Book book = new Book(ISBN, bookName, author, publisher);

            listBook.add(book);
            
            writeListBook(listBook);
        } catch (IOException ex) {
            Logger.getLogger(FrProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReadActionPerformed
        // TODO add your handling code here:
        readListBook();
    }//GEN-LAST:event_btReadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btRead;
    private javax.swing.JComboBox<String> cbPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBooks;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    private void writeListBook(ArrayList<Book> listBook) throws IOException {
        FileOutputStream fis = new FileOutputStream("book.dat");
        ObjectOutputStream oos = new ObjectOutputStream(fis);
        oos.writeObject(listBook);
        oos.close();
    }

    private void readListBook() {
        //Dieu kien du lieu xuat hien tren JTable, 
        //su dung doi tuong DefaultTableModel
        //b1: tao doi tuong DefaultTableModel 
        DefaultTableModel model = (DefaultTableModel) tbBooks.getModel();

        //b2: Doc du lieu tu file
        ArrayList<Book> listBook = null;
        try {
            FileInputStream fis = new FileInputStream("book.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);

            listBook = (ArrayList<Book>) ois.readObject();

            ois.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        //b3: Dua du lieu vao doi tuong DefaultTableModel
        for (int i = 0; i < listBook.size(); i++) {
            Object[] bookObject = new Object[]{listBook.get(i).getISBN(),
                listBook.get(i).getBookName(),
                listBook.get(i).getAuthor(),
                listBook.get(i).getPublisher()};
            
            model.addRow(bookObject);
        }
    }

    private void writeBook(Book book) throws IOException {
        FileOutputStream fis = new FileOutputStream("book.dat");
        ObjectOutputStream oos = new ObjectOutputStream(fis);
        oos.writeObject(book);
        oos.close();
    }

    private void readBook() {
        //Dieu kien du lieu xuat hien tren JTable, 
        //su dung doi tuong DefaultTableModel
        //b1: tao doi tuong DefaultTableModel 
        DefaultTableModel model = (DefaultTableModel) tbBooks.getModel();

        //b2: Doc du lieu tu file
        Book book = null;
        try {
            FileInputStream fis = new FileInputStream("book.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);

            book = (Book) ois.readObject();

            ois.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        //b3: Dua du lieu vao doi tuong DefaultTableModel
        Object[] bookObject = new Object[]{book.getISBN(),
            book.getBookName(),
            book.getAuthor(),
            book.getPublisher()};
        model.addRow(bookObject);

    }
}
